- name: Apt Update
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Install pip3
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install apt packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ pip_packages }}"