- name: Converge - Install kvm
  hosts: all
  gather_facts: yes
  become: yes
  collections:
    - fabos.kvm
  tasks:
    - name: "Include fabos.kvm.setup - install"
      include_role:
        name: fabos.kvm.setup
        tasks_from: install.yml