- name: Check input vars
  ansible.builtin.assert:
    that:
      - resource_id is defined and resource_id | length > 0

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- name: Stop vms
  community.libvirt.virt:
    name: "{{ resource_id }}"
    state: destroyed
  when: resource_id in existing_vms.list_vms

- name: Undefine vms
  community.libvirt.virt:
    name: "{{ resource_id }}"
    command: undefine
  when: resource_id in existing_vms.list_vms

- name: Remove disk files of vms
  file:
    path: "{{ libvirt_pool_dir }}/{{ resource_id }}.qcow2"
    state: absent