---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu2204
    template_name: ubuntu-22-04
  - name: ubuntu2004
    template_name: ubuntu-20-04
  - name: ubuntu1804
    template_name: ubuntu-18-04
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../default-install/converge.yml
    verify: ../default-install/verify.yml
verifier:
  name: ansible
