- name: Verify - Create VM
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Set Input vars
      ansible.builtin.include_vars:
        file: defaults.yml

    - name: Get VMs list
      community.libvirt.virt:
        command: list_vms
      register: existing_vms
      changed_when: no

    - name: Print VM list
      debug:
        var: existing_vms

    - assert:
        that:
          - existing_vms.list_vms is defined and existing_vms.list_vms | length == vms | length


    - assert:
        that: "'{{ item.resource_id }}' in {{ existing_vms.list_vms }}"
      loop: "{{ vms }}"


