- name: Converge - Delete VM
  hosts: all
  gather_facts: yes
  become: yes
  collections:
    - fabos.kvm
  tasks:
    - name: Set Input vars
      ansible.builtin.include_vars: ../default-create-vm/defaults.yml

    - name: "Include fabos.kvm.use - delete_vm"
      include_role:
        name: fabos.kvm.use
        tasks_from: delete_vm.yml
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
      vars:
        iso_key_name: "{{ vm.iso_key_name }}"
        resource_id: "{{ vm.resource_id }}"
        vm_vcpus: "{{ vm.vm_vcpus }}"
        vm_ram_mb: "{{ vm.vm_ram_mb }}"