---
# defaults file for setup
apt_packages:
  - libguestfs-tools
  - libvirt-dev
  - virtinst
  - qemu
  - qemu-system-arm
  - qemu-kvm
  - libguestfs-tools
  - libvirt-daemon-system
  - libvirt-clients
pip_packages:
  - libvirt-python
  - lxml
  - jmespath
iso_folder_abs_path: "/tmp/kvm_iso"
config_files_folder_abs_path: "/tmp/kvm_config_files"
iso:
  ubuntu_1804:
    url: "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
    virt_customize: "--firstboot-command 'growpart /dev/vda 1 && resize2fs /dev/vda1'  --copy-in {{ config_files_folder_abs_path }}/netplan-network.yaml:/etc/netplan/  --install qemu-guest-agent  --uninstall cloud-init --selinux-relabel"
  ubuntu_2004:
    url: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
    virt_customize: "--firstboot-command 'growpart /dev/vda 1 && resize2fs /dev/vda1'  --copy-in {{ config_files_folder_abs_path }}/netplan-network.yaml:/etc/netplan/  --install qemu-guest-agent  --uninstall cloud-init --selinux-relabel"
  ubuntu_2204:
    url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
    virt_customize: "--firstboot-command 'growpart /dev/vda 1 && resize2fs /dev/vda1'  --copy-in {{ config_files_folder_abs_path }}/netplan-network.yaml:/etc/netplan/  --install qemu-guest-agent  --uninstall cloud-init --selinux-relabel"
  centos_7:
      url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2111.qcow2"
  centos_8:
      url: "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2"
  centos_9:
      url: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-20220309.0.x86_64.qcow2"
